---
# tasks file for roles/k8s_base

- name: Desactivar Swap (Requisito estricto de Kubelet)
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Asegurar que el swap quede desactivado permanentemente en /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Instalar dependencias para repositorios apt sobre HTTPS
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true

- name: Crear directorio para las llaves GPG de Kubernetes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Descargar y guardar la llave GPG oficial de Kubernetes (v1.30)
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Añadir el repositorio oficial de Kubernetes
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
    state: present
    filename: kubernetes

- name: Instalar kubelet, kubeadm y kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Congelar las versiones de los binarios (Version Pinning)
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
