plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostnames:
  - instance-id

keyed_groups:
  - key: ec2_tags.Role
    prefix: role
    separator: '_'

filters:
  instance-state-name: running
  'tag:Project': devops-chair-k8s

compose:
  ec2_tags: tags
  ansible_connection: "'amazon.aws.aws_ssm'"
  ansible_aws_ssm_region: "'us-east-1'"
  # ansible_user: "ec2_tags.Role == 'nat' | ternary('ec2-user', 'ubuntu')"
