---
# tasks file for roles/install_ingress_nginx
- name: Add Ingress Nginx Helm repository
  ansible.builtin.command:
    cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Update Helm repositories
  ansible.builtin.command:
    cmd: helm repo update
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Install Nginx Ingress Controller (Host Network)
  ansible.builtin.command:
    cmd: >
      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
      --namespace ingress-nginx --create-namespace
      --set controller.hostNetwork=true
      --set controller.kind=DaemonSet
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
