---
# tasks file for roles/nat_setup

- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Install iptables service
  ansible.builtin.dnf:
    name: iptables-services
    state: present

- name: Make sure iptables service is active
  ansible.builtin.systemd:
    name: iptables
    enabled: true
    state: started

- name: Allow forwarding of return traffic
  ansible.builtin.iptables:
    chain: FORWARD
    ctstate: [ESTABLISHED, RELATED]
    jump: ACCEPT
    action: insert
  notify: Save iptables rules

- name: Allow forwarding from the VPC
  ansible.builtin.iptables:
    chain: FORWARD
    source: 10.0.0.0/16
    jump: ACCEPT
    action: insert
  notify: Save iptables rules

- name: Show primary interface.
  ansible.builtin.debug:
    msg: 'Interface {{ ansible_default_ipv4.interface }}'

- name: Enable Masquerade on dynamic default interface
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: '{{ ansible_default_ipv4.interface }}'
    jump: MASQUERADE
    state: present
  notify: Save iptables rules
