apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/lesanpi/devops-chair.git
    targetRevision: main
    path: k8s/platform-infra
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
