name: 'Terraform CD (Apply Manual)'

on:
  workflow_dispatch:
    inputs:
      confirmacion:
        description: 'Write "yes" to confirm deployment'
        required: true
        default: 'no'

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmacion == 'yes' }}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::275061641109:role/devops-chair-github-actions
          aws-region: us-east-1

      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
